"""Adăugare câmpuri cargo_type și licensePlate în tabelul User

Revision ID: 9ed03c24e496
Revises: eecef1b3d642
Create Date: 2024-05-11 12:25:16.768054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed03c24e496'
down_revision = 'eecef1b3d642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('license_plate', sa.String(length=50), nullable=True))

    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('driver_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('license_plate')
        batch_op.drop_column('cargo_type')

    # ### end Alembic commands ###
